[workspace]
members = [
    "common/common",
    "common/test_common",
    "common/build_common",
    "common/common_actor",
    "canisters/api_mock_canister",
]

[profile.release]
lto = true
opt-level = 'z'
panic = 'abort'
